#!/bin/bash

# Copyright 2016 Red Hat Inc., Durham, North Carolina.
# All Rights Reserved.
#
# openscap-daemon is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 2.1 of the License, or
# (at your option) any later version.
#
# openscap-daemon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with openscap-daemon.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors:
#   Martin Preisler <mpreisle@redhat.com>

# parent dir of this script
PARENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $PARENT_DIR > /dev/null

PYTHON_VERSIONS="$(which python2 2> /dev/null) $(which python3 2> /dev/null)"
echo "$PYTHON_VERSIONS"

for PYTHON in $PYTHON_VERSIONS;
do
    echo "Testing with python '$PYTHON'"
    export PYTHON

    ./unit/make_check || exit 1
    ./integration/make_check || exit 1

    echo
    echo
done

popd > /dev/null
